name: "Build Image"

on:
  workflow_dispatch:

env:
  tag: ghcr.io/rerigferl/vpm-packager
  
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get Version
        id: package_version
        uses: KageKirin/get-csproj-version@v1.0.0
        with:
          file: vpm-packager.csproj

      - name: Build Docker Image
        run: |
          docker build --tag ${{ env.tag }}:latest \
          --tag ${{ env.tag }}:$(echo $GITHUB_SHA | head -c7) \
          --tag ${{ env.tag }}:v${{ steps.package_version.outputs.version}} \
          . 
          docker push ${{ env.tag }}:latest
          docker push ${{ env.tag }}:$(echo $GITHUB_SHA | head -c7)
